org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.97

mod_id=gunsmiths_gadgetsn_gizmos
mod_name=Gunsmith's Gadgets 'n Gizmos
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.maxwell.gunsmiths_gadgetsn_gizmos
